unify client+server under 1 workspace
now can use just 1 patch section in .toml

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -1,9 +1,23 @@
 #!/usr/bin/bash
 
 #logout then login again, in case we're using ./run_standalone_temp.sh as the server, which means, we can't use the prev. server's creds on the new server! aka 'TokenError(Error(InvalidSignature))'
-spacetime logout
-set -e
-spacetime login --server-issued-login 127.0.0.1:3000
+#spacetime logout
+#export RUST_BACKTRACE=1
+set -x
+autoslocalscripts="autoslocalscripts"
+#^ useless
+#This works first time, the fails due to being already added!
+spacetime server add \
+--cert ../../CA/ca.crt \
+--url https://127.1.2.3:6543 \
+$autoslocalscripts \
 
-spacetime publish --project-path server quickstart-chat
+set -e
+
+#spacetime login --server-issued-login https://127.1.2.3:6543 --cert ../../CA/ca.crt
+spacetime login --server-issued-login $autoslocalscripts --cert ../../CA/ca.crt
+
+spacetime server list
+spacetime publish --yes --server $autoslocalscripts --project-path server quickstart-chat --cert ../../CA/ca.crt
+#spacetime publish --project-path server quickstart-chat --cert ../../CA/ca.crt
 echo "all good."
